name: Deploy FastAPI

on:
  push:
    branches:
      - main
      - dev

jobs:

  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Production
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}

          script: |
            set -e

            echo "========================================"
            echo "STARTING PRODUCTION DEPLOYMENT"
            echo "========================================"

            cd /root/shikshaconnect-api

            echo "Current directory:"
            pwd

            echo "Fetching latest code..."
            git fetch origin

            echo "Updating production..."
            git checkout -f main
            git reset --hard origin/main

            echo "Building Production..."
            docker compose up -d --build

            echo "Production status:"
            docker compose ps

            echo "========================================"
            echo "PRODUCTION DEPLOYMENT COMPLETE"
            echo "========================================"


  deploy-development:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Development
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}

          script: |
            set -e

            echo "========================================"
            echo "STARTING DEVELOPMENT DEPLOYMENT"
            echo "========================================"

            cd /root/shikshaconnect-api-dev

            echo "Current directory:"
            pwd

            echo "Backing up Dev .env..."
            cp .env /tmp/shikshaconnect-dev.env

            echo "Fetching latest code..."
            git fetch origin

            echo "Switching to dev branch..."
            git checkout -f dev

            echo "Resetting to latest origin/dev..."
            git reset --hard origin/dev

            echo "Restoring Dev .env..."
            cp /tmp/shikshaconnect-dev.env .env

            echo "Building and starting Dev..."
            docker compose -p shikshaconnect-dev up -d --build

            echo "Development status:"
            docker compose -p shikshaconnect-dev ps

            echo "========================================"
            echo "DEVELOPMENT DEPLOYMENT COMPLETE"
            echo "========================================"