from sqlalchemy import Column, Date, ForeignKey, Integer, String
from database.database import Base


class Student(Base):
    __tablename__ = "students"
    id = Column(Integer, primary_key=True, autoincrement=True)
    school_id = Column(Integer, ForeignKey("schools.id", ondelete="RESTRICT"), nullable=False, index=True)
    date_of_birth = Column(Date, nullable=False)
    caste_category_id = Column(Integer, ForeignKey("caste_categories.id", ondelete="RESTRICT"), nullable=False, index=True)
    fee_category_id = Column(Integer, ForeignKey("fee_categories.id", ondelete="RESTRICT"), nullable=False, index=True)
    session_id = Column(Integer, ForeignKey("sessions.id", ondelete="RESTRICT"), nullable=False, index=True)
    class_id = Column(Integer, ForeignKey("classes.id", ondelete="RESTRICT"), nullable=False, index=True)
    first_name = Column(String(255), nullable=False)
    last_name = Column(String(255), nullable=False)
    mobile_number = Column(String(20), nullable=False)
    gender = Column(String(50), nullable=False)
    email = Column(String(255), nullable=False)
    nationality = Column(String(100), nullable=False)
    father_name = Column(String(255), nullable=False)
    father_contact_no = Column(String(20), nullable=False)
    father_aadhaar_no = Column(String(20), nullable=False)
    mother_name = Column(String(255), nullable=False)
    line_1 = Column(String(500), nullable=False)
    city = Column(String(255), nullable=False)
    country = Column(String(100), nullable=False)
    state = Column(String(255), nullable=False)
    pin_code = Column(String(20), nullable=False)
    middle_name = Column(String(255), nullable=True)
    blood_group = Column(String(10), nullable=True)
    religion = Column(String(100), nullable=True)
    aadhaar_number = Column(String(20), nullable=True)
    permanent_education_no = Column(String(100), nullable=True)
    father_secondary_number = Column(String(20), nullable=True)
    father_qualification = Column(String(255), nullable=True)
    father_occupation = Column(String(255), nullable=True)
    father_office_address = Column(String(1000), nullable=True)
    mother_contact_no = Column(String(20), nullable=True)
    mother_secondary_number = Column(String(20), nullable=True)
    mother_qualification = Column(String(255), nullable=True)
    mother_occupation = Column(String(255), nullable=True)
    mother_aadhaar_no = Column(String(20), nullable=True)
    mother_office_address = Column(String(1000), nullable=True)
    guardian_name = Column(String(255), nullable=True)
    relation_with_student = Column(String(100), nullable=True)
    guardian_primary_contact_no = Column(String(20), nullable=True)
    guardian_secondary_contact_no = Column(String(20), nullable=True)
    guardian_email = Column(String(255), nullable=True)
    guardian_address = Column(String(1000), nullable=True)
    line_2 = Column(String(500), nullable=True)
    address_type = Column(String(100), nullable=True)
